# Generated by Django 4.0.8 on 2022-12-21 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_comun', '0001_initial'),
        ('receipt', '0002_receipt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='common_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_area_receipt', to='area_comun.areacomun', verbose_name='Area Comun'),
        ),
    ]
