# Generated by Django 4.0.8 on 2022-12-21 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('area_comun', '0001_initial'),
        ('receipt', '0003_receipt_common_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='common_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commonarea_receipt', to='area_comun.areacomun', verbose_name='Area Comun'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receipt', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
