# Generated by Django 4.0.8 on 2022-12-28 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0006_receipt_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_reservation_confirmed',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Reserva Confirmada?'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 1, 46, 52, 658572), verbose_name='Fecha de Reserva'),
        ),
    ]
