# Generated by Django 4.0.8 on 2022-12-28 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0008_remove_receipt_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='filepath',
            field=models.TextField(default='', max_length=500, verbose_name='Ubicacion del Recibo'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='begin_reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 2, 25, 46, 671754), verbose_name='Inicio de Reserva'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='end_reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 2, 25, 46, 671754), verbose_name='Fin de Reserva'),
        ),
    ]
