# Generated by Django 4.0.8 on 2022-12-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0009_receipt_filepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='begin_reservation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Reserva'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='end_reservation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de Reserva'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='filepath',
            field=models.FilePathField(blank=True, null=True, verbose_name='Ubicacion del Recibo'),
        ),
    ]
