# Generated by Django 4.0.8 on 2022-12-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0010_alter_receipt_begin_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='filepath',
            field=models.FilePathField(blank=True, max_length=500, null=True, verbose_name='Ubicacion del Recibo'),
        ),
    ]
