# Generated by Django 4.0.8 on 2022-12-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0011_alter_receipt_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='filepath',
        ),
        migrations.AddField(
            model_name='receipt',
            name='filename',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
