# Generated by Django 4.0.8 on 2022-12-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('descripcion', models.TextField(max_length=100)),
                ('mobiliario', models.TextField(default='Ninguno', max_length=100)),
                ('costo', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
